Vagrant.configure("2") do |config|

  NAME = "sensor_test"

  config.vm.box = "debian/bullseye64"
  config.vm.box_check_update = false
  config.vm.define NAME
  # config.vm.network :public_network, ip: "192.168.1.77"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |v|
    v.name = NAME
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update && sudo apt upgrade -y
  SHELL
end
